package com.baeldung.optaplanner

import com.baeldung.optaplanner.Person;
import com.baeldung.optaplanner.Person.Gender;
import com.baeldung.optaplanner.Person.Role;
import com.baeldung.optaplanner.Schedule;
import com.baeldung.optaplanner.Schedule.Type;
import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScoreHolder;

global HardSoftScoreHolder scoreHolder;

function int pow2(int value) {
    return value * value;
}

// "每一個排班必須在一個的時間進行" 跟 "每一個排班必須有一個項目" 已經內建

rule "每一個排班必須分派給一個人"
    when
        Schedule( assignee == null );
    then
        scoreHolder.addHardConstraintMatch(kcontext, -1);
end

// "每一個排班的時間必須是工作天" 已經內建

// "每一個項目在同一個時間必須不超過一個的在進行" 已經內建

rule "每一個人力在同一個時間必須不被分配超過一個排班"
    when
        Schedule($assignee : assignee, $time : time, $type : type, $id : id, assignee != null)
        Schedule(assignee == $assignee, time == $time, id > $id)
    then
        scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "每一個人力在同一個時間必須不被分配超過一個排班 - 門診"
    when
        $assignee : Person()
        $sched : Schedule(assignee == $assignee)
        Schedule(time == $sched.time) from $assignee.getOPDSchedule()
    then
        scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "每一個一般R人力儘量一個月內有 3 次排班的項目是抹片"
    when
        $person : Person(role == Role.NORMAL)
        accumulate(
            $assignment : Schedule(assignee == $person, type == Type.PAP),
            $total : count($assignment)
        )
    then
        scoreHolder.addSoftConstraintMatch(kcontext, -pow2($total.intValue() - 3));
end

rule "每一個人力儘量一個月內有 3 次排班的項目是晨會投影片或科會投影片"
    when
        $person : Person()
        accumulate(
            $assignment : Schedule(assignee == $person, type == Type.MORNINGMEETING_SLIDE || type == Type.W5MEETING_SLIDE),
            $total : count($assignment)
        )
    then
        scoreHolder.addSoftConstraintMatch(kcontext, -pow2($total.intValue() - 3));
end

rule "每一個人力儘量一個月內有 3 次排班的項目是晨會記錄或科會記錄"
    when
        $person : Person()
        accumulate(
            $assignment : Schedule(assignee == $person, type == Type.MORNINGMEETING_NOTE || type == Type.W5MEETING_NOTE),
            $total : count($assignment)
        )
    then
        scoreHolder.addSoftConstraintMatch(kcontext, -pow2($total.intValue() - 3));
end

rule "每一個人力儘量一個月內有 1 次排班的項目是景福講座"
    when
        $person : Person()
        accumulate(
            $assignment : Schedule(assignee == $person, type == Type.JINGFUMEETING),
            $total : count($assignment)
        )
    then
        scoreHolder.addSoftConstraintMatch(kcontext, -pow2($total.intValue() - 1));
end

rule "每一個人力在同一天儘量不要上午下午都被排班"
    when
        $person : Person()
        Schedule($date : time.localDate, $id : id, assignee == $person)
        Schedule(time.localDate == $date, assignee == $person, id > $id)
    then
        scoreHolder.addSoftConstraintMatch(kcontext, -100);
end

rule "每一個人力在同一天儘量不要上午下午都被排班 - 門診"
    when
        $person : Person()
        Schedule($date : time.localDate, $id : id, assignee == $person)
        Schedule(time.localDate == $date) from $person.getOPDSchedule()
    then
        scoreHolder.addSoftConstraintMatch(kcontext, -20);
end

rule "同一天內項目爲抹片的排班希望至少有一個人力是女生"
    when
        Schedule($date : time.localDate, $id : id, type == Type.PAP, assignee!.gender == Gender.MALE)
        Schedule(time.localDate == $date, type == Type.PAP, assignee!.gender == Gender.MALE, id > $id)
    then
        scoreHolder.addSoftConstraintMatch(kcontext, -1);
end
